listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
persistence true
persistence_location /mosquitto/data/

# --- MQTT Bridge ---
connection bridge-to-primary
address 113.161.220.166:1883
remote_username meterMQTT
remote_password meterMQTT
topic meter/+/data out 0
topic meter/+/ota/status out 0
topic meter/+/control in 0
topic firmwareUpdateOTA/device/+ in 0
cleansession false
notifications true
restart_timeout 10
